#!/bin/bash
set -e

if command -v aws &>/dev/null; then
    echo "AWS CLI already installed: $(aws --version)"
else
    echo "Installing AWS CLI..."
    curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip -q -o awscliv2.zip
    ./aws/install
    rm -rf aws awscliv2.zip
fi
